backend:
  name: github
  repo: JonasHeinickeBio/anja-heinicke-coaching
  branch: main

media_folder: "jekyll-site/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    folder: "jekyll-site"
    create: false
    delete: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "default"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Body", name: "body", widget: "markdown"}